# Copyright (C) 2020  The Project U-Ray Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

N ?= 10
SEGMATCH_ARGS?=-c 1
GENERATE_ARGS?=--oneval 1 --design params.csv --dword 2 --auto_frame
include ../fuzzaddr/common.mk
