os: linux
language: python
python: 3.6
addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - clang-format-5.0
      - g++-6
      - xsltproc

install:
  - export CC=gcc-6
  - export CXX=g++-6
  - make env


jobs:
  include:
    # State 1 - Tests
    - stage: "Tests"
      name: "C++ Tests"
      script: make test-cpp

    - name: "Python Tests"
      script: make test-py

    - name: "Format"
      script:
        - make format
        - test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }

    - name: "License Checks"
      script:
        - ./.github/check_license.sh
        - ./.github/check_python_scripts.sh
