# Copyright (C) 2020  The Project U-Ray Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

N ?= 15
GENERATE_ARGS?=--oneval 0 --design params.csv --dword 1 --dframe 0A --filter_word 45,46
include ../fuzzaddr/common.mk

